# arxivの学問領域の指定
subject: 'cs'

# 検索キーワード
keywords:
        cyclic proof: 1
        fibration: 3
        fixed point: 3
        category theory: 3

subjects:
  - cs.CL
  - cs.LO
  - math.CT
  - math.LO
